#ifndef __ATTRIBUTELIST__    
#define __ATTRIBUTELIST__

#include "Attribute.idl"
#include "NoSuchAttributeException.idl"

//module DOM {

   interface AttributeList {
     Attrib           getAttribute(in wstring attrName);
     Attrib           setAttribute(in Attrib attr);
     Attrib           remove(in wstring attrName)
       raises (NoSuchAttributeException);
     Attrib           item(in unsigned long index)
       raises (NoSuchAttributeException);
     unsigned long       getLength();
  };

//}


#endif