#ifndef __ENTITYREFERENCE__    
#define __ENTITYREFERENCE__

module DOM {

   interface EntityReference {
     attribute boolean        isExpanded;
     void                expand(in  );
  };

}


#endif