#ifndef __NODEITERATOR__    
#define __NODEITERATOR__

interface Node;

#include "Node.idl"

// module DOM {

   interface NodeIterator {
     unsigned long       getLength();
     unsigned long       getCurrentPos();
     boolean             atFirst();
     boolean             atLast();
     Node                toNextNode();
     Node                toPrevNode();
     Node                toFirstNode();
     Node                toLastNode();
     Node                moveTo(in long n);
  };

// };


#endif
