#ifndef __SECTIONS__    
#define __SECTIONS__

//hb////-*-Mode: C++-*-////////////////////////////////////////////////////////
//                                                                           //
// NAME        :                                                             //
// DESCRIPTION :                                                             //
// HISTORY     :                                                             //
//                                                                           //
//he///////////////////////////////////////////////////////////////////////////

interface CDATASection : Node {
  attribute wstring content;
};
#endif