#ifndef __TEXT__    
#define __TEXT__


#include "Node.idl"

// module DOM {

   interface Text : Node {
     attribute wstring        data;
     void                append(in wstring newData);
     void                insert(in long offset, 
                                in wstring newData);
     void                delete(in long offset, 
                                in long count);
     void                replace(in long offset, 
                                 in long count, 
                                 in wstring newData);
//     void                splice(in Element element, 
//                                in long offset, 
//                                in long count);
// NOTE: This method will possibly be moved to
// another class (Utility?)
// There will possibly be another splice method instead, which
// operates only on the text in this class.
// The new splice will most likely look like this:
     Text splice(in long offset, in long count);
     wstring            range(in long offset, in long count);
  };

//};


#endif
