#ifndef __XMLNODE__    
#define __XMLNODE__

module DOM {

   interface XMLNode {
     Node                getParentXMLNode(in boolean expandEntities);
     NodeIterator        getChildXMLNodes(in boolean expandEntities);
     boolean             hasChildXMLNodes(in boolean expandEntities);
     Node                getFirstXMLChild(in boolean expandEntities);
     Node                getPreviousXMLSibling(in boolean expandEntities);
     Node                getNextXMLSibling(in boolean expandEntities);
     EntityReference     getEntityReference();
     EntityDeclaration   getEntityDeclaration();
  };

}


#endif