/*$Id: Figure.idl,v 1.6 2000/12/21 21:05:43 stefan Exp $
 *
 * This source file is a part of the Berlin Project.
 * Copyright (C) 1999 Stefan Seefeld <stefan@berlin-consortium.org> 
 * http://www.berlin-consortium.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
 * MA 02139, USA.
 */

#ifndef _Warsaw_Figure_idl
#define _Warsaw_Figure_idl

#include <Warsaw/Graphic.idl>

module Figure
{
//   typedef Warsaw::Path Vertices;
  typedef short Mode;
  const Mode fill = 1;
  const Mode outline = 2;

  interface FigureBase : Warsaw::Graphic
    {
//       //. The Vertices type defines a sequence of vertex structures
//       //. for figures with an arbitrary number of vertices,
//       //. such as polygons and B-splines.
      
      //   attribute Style figure_style;
      //   attribute Mode figure_mode;
      
      attribute Mode type;
      attribute Warsaw::Color foreground;
      attribute Warsaw::Color background;
      
      void resize();
    };

    interface Point : FigureBase
	{
	  attribute Warsaw::Vertex pt;
	};
      
      interface Line : FigureBase
	{
	  attribute Warsaw::Vertex pt1, pt2;
	};
      
      interface Rectangle : FigureBase
	{
	  attribute Warsaw::Vertex pt1, pt2;
	};
      
      interface Circle : FigureBase
	{
	  attribute Warsaw::Vertex center;
	  attribute Warsaw::Coord radius;
	};
      
      interface Ellipse : FigureBase
	{
	  attribute Warsaw::Vertex center;
	  attribute Warsaw::Coord radius1;
	  attribute Warsaw::Coord radius2;
	};
      
      interface Path : FigureBase
	{
	  attribute Warsaw::Path handles;        
	  readonly attribute boolean closed;
	  //     attribute boolean curved;
	};
    };

#endif
