/*$Id: Server.idl,v 1.5 2000/09/19 21:11:02 stefan Exp $
 *
 * This source file is a part of the Berlin Project.
 * Copyright (C) 1998 Graydon Hoare <graydon@pobox.com> 
 * Copyright (C) 2000 Stefan Seefeld <stefan@berlin-consortium.org> 
 * http://www.berlin-consortium.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
 * MA 02139, USA.
 */
#ifndef _Warsaw_Server_idl
#define _Warsaw_Server_idl

#include <Warsaw/Kit.idl>

module Warsaw
{
  interface ClientContext;

  exception SecurityException {};
  exception SingletonFailureException {};
  exception CreationFailureException {};
  
  //. the ServerContext is an object you pick up from the berlin
  //. server's root ContextManager, and which you use to create all
  //. generic interfaces (kits, plugins, etc).
  interface ServerContext
    {
      //. this is the entry point to generic object creation on a server.
      Kit resolve(in string type, in Kit::PropertySeq attr)
	raises (SecurityException, CreationFailureException);
      
      //. access to singletons (like the fontManager) this way
      void set_singleton(in string name, in Object singleton) 
	raises (SecurityException, SingletonFailureException);
      
      void remove_singleton(in string name)
	raises (SecurityException, SingletonFailureException);
      
      Object get_singleton(in string name) 
	raises (SecurityException, SingletonFailureException);
    };
  
  interface Server
    //. this is the "super-context" -- the entry point for all new contexts.
    {
      ServerContext create_server_context(in ClientContext C) raises (SecurityException);
    };
};

#endif
