/*$Id: Stage.idl,v 1.5 2000/09/19 21:11:02 stefan Exp $
 *
 * This source file is a part of the Berlin Project.
 * Copyright (C) 1999, 2000 Stefan Seefeld <stefan@berlin-consortium.org> 
 * http://www.berlin-consortium.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
 * MA 02139, USA.
 */
#ifndef _Layout_Stage_idl
#define _Layout_Stage_idl

#include <Warsaw/Graphic.idl>

module Layout
{
  interface StageHandle;
  
  //. A stage allows its children to be placed at any position and
  //. layering.
  interface Stage : Warsaw::Graphic
    {
      typedef long Index;
      Warsaw::Region bbox();
      long layers();
      StageHandle layer(in Index l);
      
      void begin();
      void end();
      
      StageHandle insert(in Warsaw::Graphic g, in Warsaw::Vertex position, in Warsaw::Vertex size, in Index layer);
    };
  
  interface StageHandle
    {
      Stage           parent();
      Warsaw::Graphic child();
      void            remove();
      attribute Warsaw::Vertex position;
      attribute Warsaw::Vertex size;
      attribute Stage::Index layer;
    };
};

#endif
