#!/usr/bin/perl
# This is a wrapper script for the berlin demos. *** Please ***
# do not invoke this directly, nothing will happen.

$ENV{'WARSAW'} = '/usr/lib/Berlin/Plugins';
$ENV{'LD_LIBRARY_PATH'} = $ENV{'WARSAW'};

$0 =~ /berlin-(.*)/;
$demo = $1;

system( "/usr/lib/Berlin/bin/$demo" );
