/*$Id: BoundedRange.idl,v 1.1 1999/04/13 20:56:28 gray Exp $
 *
 * This source file is a part of the Berlin Project.
 *
 * Copyright (C) 1999 Stefan Seefeld <seefelds@magellan.umontreal.ca> 
 *
 * http://www.berlin-consortium.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
 * MA 02139, USA.
 */
#ifndef _BoundedRange_idl
#define _BoundedRange_idl

#include <Subject.idl>
#include <Types.idl>

interface BoundedRange : Subject
{
  attribute Coord lower;
  attribute Coord upper;
  attribute Coord step;
  attribute Coord page;
  attribute Coord lvalue;
  attribute Coord uvalue;
  void forward();
  void backward();
  void fastforward();
  void fastbackward();
  void begin();
  void end();
  void adjust(in Coord d);
};

#endif /* _BoundedRange_idl */
