/*$Id: ImageKit.idl,v 1.3 1999/07/07 04:12:45 gray Exp $
 *
 * This source file is a part of the Berlin Project.
 * Copyright (C) 1999 Brent Fulgham <bfulgham@debian.org>
 * Copyright (C) 1999 Stefan Seefeld <seefelds@MAGELLAN.UMontreal.CA>
 * http://www.berlin-consortium.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
 * MA 02139, USA.
 */

#ifndef _ImageKit_idl
#define _ImageKit_idl

#include "Types.idl"
#include "Cloneable.idl"
#include "Raster.idl"

/*
 * Raster holds the detailed image data corresponding to a picture
 * or texture mapping on the screen (or in memory).
 *
 * It is generally contained within an Image object, which handles
 * all of the nasty details related to layout and so forth.
 *
 */

interface ImageKit : Cloneable
{
	Raster empty();				// Returns a null raster
	Raster create(in string file);		// Create from a file
};

#endif /* _ImageKit_idl */
