/*$Id: Pencil.idl,v 1.5 1999/04/14 02:51:26 gray Exp $
 *
 * This source file is a part of the Berlin Project.
 * Copyright (C) 1999 Stefan Seefeld <seefelds@magellan.umontreal.ca> 
 * http://www.berlin-consortium.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
 * MA 02139, USA.
 */
#ifndef _Pencil_idl
#define _Pencil_idl

#include <Types.idl>

interface Drawable;

// note: any given pencil was manufactured very specifically with a given
// set of style parameters. These methods only control its geometry, not it's
// color/texture/width/pattern etc.

interface Pencil
{
  void drawPath(in Path p);
  void drawPatch(in Patch p);
  void drawRect(in Vertex lower, in Vertex upper);
  void drawEllipse(in Vertex lower, in Vertex upper);
};

#endif /* _Pencil_idl */
