/*$Id: Stage.idl,v 1.5 1999/10/01 16:48:39 gray Exp $
 *
 * This source file is a part of the Berlin Project.
 * Copyright (C) 1999 Stefan Seefeld <seefelds@magellan.umontreal.ca> 
 * http://www.berlin-consortium.org
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge,
 * MA 02139, USA.
 */
#ifndef _Stage_idl
#define _Stage_idl

#include <Graphic.idl>

interface StageHandle;

interface Stage : Graphic
{
  typedef long Index;
  Region bbox();
  long layers();
  StageHandle layer(in Index l);

  void begin();
  void end();

  StageHandle insert(in Graphic g, in Vertex p, in Vertex size, in Index l);
  void remove(in StageHandle h);
};

interface StageHandle
{
  Stage     parent();
  Graphic   child();
  attribute Vertex position;
  attribute Vertex size;
  attribute Stage::Index layer;
};

#endif /* _Stage_idl */
