#ifndef _TextKit_idl
#define _TextKit_idl

//
// $Id: TextKit.idl,v 1.4 1999/09/17 19:15:23 gray Exp $
//
// This source file is a part of the Berlin Project.
// Copyright (C) 1998 Graydon Hoare <graydon@pobox.com> 
// http://www.berlin-consortium.org
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public License
// as published by the Free Software Foundation; either version 2 of
// the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this program; if not, write to the Free Software
// Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//
//

#include "Cloneable.idl"
#include "Style.idl"
#include "Text.idl"

// a TextKit serves as a registry for available fonts, as well as
// a text-encapsulation service, for producing flyweights which
// will render themselves using the appropriate facility of a drawingKit.
// textChunk flyweights will produce text, fontChange flyweights will try
// to set the current font. simple as that.

interface DrawingKit;

interface TextKit : Cloneable {
  readonly attribute Text::FontDescriptorSeq fonts;
  readonly attribute DrawingKit dk;
  Graphic chunk(in Unistring u, in Text::Font f);    
  Graphic fontChange(in Text::FontDescriptor fd, in Style::Spec sty);    
};

#endif
