//
// $id:$
//
// This source file is a part of the Berlin Project.
// Copyright (C) 1998 The Berlin Consortium 
// http://www.berlin-consortium.org
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public License
// as published by the Free Software Foundation; either version 2 of
// the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this program; if not, write to the Free Software
// Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//
// Author: ANOQ of the Sun
// EMail: anoq@berlin-consortium.org or anoq@vip.cybercity.dk

// Note: This is just a stripped down version of omniORB's
//       .hh file generated by omniidl2

#ifndef __AttributeList_hh__
#define __AttributeList_hh__

#include "support/dom/nocorba/CORBA.h"

#include "support/dom/nocorba/Attribute.hh"
#include "support/dom/nocorba/domDefs.hh"
#include "support/dom/nocorba/Node.hh"
#include "support/dom/nocorba/NoSuchAttributeException.hh"
#include "support/dom/nocorba/NotMyChildException.hh"
#include "support/dom/nocorba/NodeIterator.hh"
#ifndef __AttributeList__
#define __AttributeList__
class   AttributeList;
typedef AttributeList* AttributeList_ptr;
typedef AttributeList_ptr AttributeListRef;
#endif

class AttributeList
{
public:

  virtual Attrib_ptr  getAttribute ( const wstring & attrName ) = 0;
  virtual Attrib_ptr  setAttribute ( Attrib_ptr  attr ) = 0;
  virtual Attrib_ptr  remove ( const wstring & attrName ) = 0;
  virtual Attrib_ptr  item ( CORBA::ULong  index ) = 0;
  virtual CORBA::ULong  getLength (  ) = 0;
  //static AttributeList_ptr _duplicate(AttributeList_ptr);
  static AttributeList_ptr _narrow(CORBA::Object_ptr)
    { return (AttributeList_ptr)0; }
  //static AttributeList_ptr _nil();

protected:

  AttributeList()
  { }
  virtual ~AttributeList() {}
};

class _sk_AttributeList :  public virtual AttributeList
{};

#endif // __AttributeList_hh__
