//
// $id:$
//
// This source file is a part of the Berlin Project.
// Copyright (C) 1998 The Berlin Consortium 
// http://www.berlin-consortium.org
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public License
// as published by the Free Software Foundation; either version 2 of
// the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this program; if not, write to the Free Software
// Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//
// Author: ANOQ of the Sun
// EMail: anoq@berlin-consortium.org or anoq@vip.cybercity.dk

// Note: This is just a stripped down version of omniORB's
//       .hh file generated by omniidl2

#ifndef __ProcessingInstruction_hh__
#define __ProcessingInstruction_hh__

#include "support/dom/nocorba/CORBA.h"

#include "support/dom/nocorba/Node.hh"
#include "support/dom/nocorba/domDefs.hh"
#include "support/dom/nocorba/NoSuchAttributeException.hh"
#include "support/dom/nocorba/NotMyChildException.hh"
#include "support/dom/nocorba/NodeIterator.hh"
#ifndef __ProcessingInstruction__
#define __ProcessingInstruction__
class   ProcessingInstruction;
typedef ProcessingInstruction* ProcessingInstruction_ptr;
typedef ProcessingInstruction_ptr ProcessingInstructionRef;
#endif

class ProcessingInstruction :  public virtual Node
{
public:

  virtual wstring * name ()  = 0;
  virtual void name (const wstring & _value) = 0;
  virtual wstring * data ()  = 0;
  virtual void data (const wstring & _value) = 0;
  //static ProcessingInstruction_ptr _duplicate(ProcessingInstruction_ptr);
  static ProcessingInstruction_ptr _narrow(CORBA::Object_ptr)
    { return (ProcessingInstruction_ptr)0; }
  //static ProcessingInstruction_ptr _nil();

protected:

  ProcessingInstruction()
  {}
  virtual ~ProcessingInstruction() {}
};

class _sk_ProcessingInstruction :  public virtual _sk_Node, public virtual ProcessingInstruction
{};

#endif // __ProcessingInstruction_hh__
